#! /usr/bin/env ruby
$: << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))
require 'rubygems'
require 'json'
require 'mysql2'

client = Panoptimon::Collector::MySQL.new(JSON.parse(ARGV[0]))
puts JSON.generate(client.query)

